/**
 * Legacy native carousel slides — not used on web home.
 * Kept separate so web bundles do not evaluate 15 unused `require()` assets.
 */

export const HOME_HERO_CAROUSEL_SLIDES = [
  {
    key: "hero-1",
    image: require("../../assets/marketing/hero-slide-1.jpg"),
    title: "Heritage craft, delivered",
    subtitle: "Fast delivery. Fresh picks. Curated quality.",
    cta: "Explore collection",
    action: "featured",
  },
  {
    key: "hero-2",
    image: require("../../assets/marketing/hero-slide-2.jpg"),
    title: "Fresh picks, daily",
    subtitle: "Handpicked essentials with premium freshness and reliable quality.",
    cta: "Explore fresh",
    action: "featured",
  },
  {
    key: "hero-3",
    image: require("../../assets/marketing/hero-slide-3.jpg"),
    title: "Smooth checkout",
    subtitle: "Simple cart flow, faster ordering, and a cleaner shopping experience.",
    cta: "Start shopping",
    action: "catalog",
  },
  {
    key: "hero-4",
    image: require("../../assets/marketing/hero-slide-04-wa.jpeg"),
    title: "Pure & natural",
    subtitle: "Thoughtfully sourced products you can trust for your home and family.",
    cta: "Shop now",
    action: "catalog",
  },
  {
    key: "hero-5",
    image: require("../../assets/marketing/hero-slide-05-wa.jpeg"),
    title: "Small batch quality",
    subtitle: "Limited runs and careful selection—flavour and freshness first.",
    cta: "See highlights",
    action: "featured",
  },
  {
    key: "hero-6",
    image: require("../../assets/marketing/hero-slide-06-wa.jpeg"),
    title: "From our kitchen to yours",
    subtitle: "Celebrate tradition with staples that feel premium every day.",
    cta: "Browse catalog",
    action: "catalog",
  },
  {
    key: "hero-7",
    image: require("../../assets/marketing/hero-slide-07.png"),
    title: "Curated for you",
    subtitle: "A storefront experience tuned for quick discovery on phone and web.",
    cta: "Explore collection",
    action: "featured",
  },
  {
    key: "hero-8",
    image: require("../../assets/marketing/hero-slide-08.png"),
    title: "COD & reliable delivery",
    subtitle: "Order with confidence—clear updates and dependable fulfilment.",
    cta: "Start shopping",
    action: "catalog",
  },
  {
    key: "hero-9",
    image: require("../../assets/marketing/hero-slide-09.png"),
    title: "Premium presentation",
    subtitle: "Packaging and picks that match the care behind every product.",
    cta: "Shop now",
    action: "catalog",
  },
  {
    key: "hero-10",
    image: require("../../assets/marketing/hero-slide-10.png"),
    title: "Your everyday essentials",
    subtitle: "Stock up on favourites without compromising on taste or authenticity.",
    cta: "See highlights",
    action: "featured",
  },
  {
    key: "hero-11",
    image: require("../../assets/marketing/hero-slide-11.png"),
    title: "Crafted selection",
    subtitle: "We spotlight items that earn a place on your shelf.",
    cta: "Browse catalog",
    action: "catalog",
  },
  {
    key: "hero-12",
    image: require("../../assets/marketing/hero-slide-12.png"),
    title: "Bright, modern shopping",
    subtitle: "A calm, focused layout on web and mobile—find what you need faster.",
    cta: "Explore collection",
    action: "featured",
  },
  {
    key: "hero-13",
    image: require("../../assets/marketing/hero-slide-13.png"),
    title: "Trust in every order",
    subtitle: "Transparent quality, responsive support, and a cart that stays in sync.",
    cta: "Start shopping",
    action: "catalog",
  },
  {
    key: "hero-14",
    image: require("../../assets/marketing/hero-slide-14.png"),
    title: "Made to impress",
    subtitle: "Gift-ready picks and staples that look as good as they perform.",
    cta: "Shop now",
    action: "catalog",
  },
  {
    key: "hero-15",
    image: require("../../assets/marketing/hero-slide-15.png"),
    title: "Welcome to the experience",
    subtitle: "Scroll the catalog, save your address, and checkout in minutes.",
    cta: "See highlights",
    action: "featured",
  },
];

export const HOME_HERO_SLIDE_IMAGES = HOME_HERO_CAROUSEL_SLIDES.map((s) => s.image);
