const COMPARE_DEFAULT_ROWS = [
  {
    id: "compare-milk",
    order: 0,
    enabled: true,
    label: "Milk source",
    ours: "A2 milk from indigenous Kankrej cows",
    ordinary: "A1 from crossbred or HF cows",
    oursImageUrl: "",
    ordinaryImageUrl: "",
  },
  {
    id: "compare-method",
    order: 1,
    enabled: true,
    label: "Method",
    ours: "Traditional Bilona curd-churned ghee",
    ordinary: "Factory cream separation",
    oursImageUrl: "",
    ordinaryImageUrl: "",
  },
  {
    id: "compare-feed",
    order: 2,
    enabled: true,
    label: "Feed & ethics",
    ours: "Grass-fed, free-grazing, ethically raised",
    ordinary: "Confined commercial farming",
    oursImageUrl: "",
    ordinaryImageUrl: "",
  },
  {
    id: "compare-cooking",
    order: 3,
    enabled: true,
    label: "Cooking",
    ours: "Wood-fired slow cooking for aroma & grain",
    ordinary: "High-heat industrial processing",
    oursImageUrl: "",
    ordinaryImageUrl: "",
  },
  {
    id: "compare-purity",
    order: 4,
    enabled: true,
    label: "Purity",
    ours: "Zero preservatives, additives, or adulteration",
    ordinary: "Often blended or stabilised",
    oursImageUrl: "",
    ordinaryImageUrl: "",
  },
  {
    id: "compare-packaging",
    order: 5,
    enabled: true,
    label: "Packaging",
    ours: "Small-batch, glass-bottled freshness",
    ordinary: "Mass-produced plastic packaging",
    oursImageUrl: "",
    ordinaryImageUrl: "",
  },
];

const COMPARE_SECTION_DEFAULTS = {
  enabled: true,
  eyebrow: "What makes us different",
  title: "Ours vs ordinary ghee",
  subtitle: "Most shelves sell factory-processed fat. We sell heritage.",
  filmLabel: "The difference",
  storyChapter: "Chapter II",
  openingLine: "Two paths. One golden jar. This is where heritage meets the shelf.",
  oursLabel: "KankreG",
  ordinaryLabel: "Ordinary",
  rows: COMPARE_DEFAULT_ROWS,
};

module.exports = {
  COMPARE_DEFAULT_ROWS,
  COMPARE_SECTION_DEFAULTS,
};
